You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"



class Solution {
    public char findTheDifference(String s, String t) {

        int sumS=0;
        int sumT=0;
        for(char ch:s.toCharArray())
        {
            sumS+=ch;

        }

        for(char ch:t.toCharArray())
        {
            sumT+=ch;
        }

        return (char) (sumT-sumS);
        
    }
}
Output: "y"
 